### PR TITLE
Feature/receivers in property lambdas

### LINKED ISSUE #18: Use receivers for the property lambdas.
**Describe the problem or limitation you are having in your project:**
Local value modification work-around is somewhat annoying.

**Describe how this feature / enhancement will help you overcome this problem or limitation:**
By changing the dsl-like interface like `position { it.x = 1 }` to using a receiver instead, the code will look like `position { x = 1 }` instead. Ie. not require the `it`

Not sure it this has ever been discussed or if it's a good solution.

Maybe it is possible to circumvent the problem by using delegates, or heck, maybe one doesn't want to circumvent the problem at all.

**Show a mock up screenshots/video or a flow diagram explaining how your proposal will work:**

**Describe implementation detail for your proposal (in code), if possible:**
```diff
diff --git a/tools/api-classes-generator/src/main/kotlin/Class.kt b/tools/api-classes-generator/src/main/kotlin/Class.kt
index 681cf69..501f204 100644
--- a/tools/api-classes-generator/src/main/kotlin/Class.kt
+++ b/tools/api-classes-generator/src/main/kotlin/Class.kt
@@ -231,7 +231,7 @@ class Class(
                                     ParameterSpec.builder(
                                             "schedule",
                                             LambdaTypeName.get(
-                                                    parameters = *arrayOf(parameterTypeName),
+                                                    receiver = parameterTypeName,
                                                     returnType = ClassName("kotlin", "Unit")
                                             )
                                     ).build()
```
**If this enhancement will not be used often, can it be worked around with a few lines of code?:**

**Is there a reason why this should be in this project and not individually solved?:**
The code is generated by the annotation processor.

### PR DESCRIPTION
**Pull request by lassem**
Note that the base branch is `feature/update-to-godot-3.2`

Fixes #18 

Changes the generation of property accessor dsl interface to use receivers instead of a lambda argument.

So `translation { it.x = 1.0 }` becomes `translation { x = 1.0 }` and so forth.

### CODE REVIEW

**Comment by chippmann** [comment]
@lassem I didn't look into it in detail yet but one thing i noted: the documentation change is missing. Could you please also change it if you have time?
Otherwise I'll do it.
One Note: as this is based off the 3.2 branch, we'll merge it once that's done. So if you want to use it, you have to build it locally to use it in a project.

**Comment by chippmann** [comment]
@lassem Thank you very much!

**Comment by chippmann** [comment]
@lassem As you may saw just now we moved to project to a new repo
During this move this pull request was lost.
Do you want to recreate it in the new repo (so you are the PR contributor ;-) ) or should i do it for you?
Sorry for the inconvenience but this should help the project very much in the long term.

**Comment by lassem** [comment]
Moved to new repo

**Pull request closed without merging**
